insert into comment_entity (createdAt, rating, content, authorId) values ('2022-04-26 11:35:51', 1, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 1);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-04-25 22:59:50', 2, 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 2);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-11-27 02:59:36', 1, 'Curabitur convallis.', 3);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-06-08 22:02:33', 1, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 4);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-01-13 18:46:25', 1, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 5);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-10-25 03:46:26', 4, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 6);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-08-12 23:35:55', 1, 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 7);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-10-25 06:11:27', 3, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 8);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-04-10 13:42:42', 3, null, 9);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-03-24 03:01:48', 5, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 10);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-07-29 22:25:06', 5, null, 11);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-04-27 22:14:46', 1, 'Vivamus vel nulla eget eros elementum pellentesque.', 12);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-11-28 11:18:35', 5, null, 13);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-11-23 07:30:31', 5, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 14);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-11-27 20:22:50', 5, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 15);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-04-21 01:10:41', 4, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 16);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-10-12 05:48:37', 3, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 17);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-06-22 19:39:03', 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 18);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-09-08 12:39:52', 5, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 19);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-08-03 04:02:06', 1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 20);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-11-07 20:10:13', 4, 'Aliquam erat volutpat.', 21);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-02-22 12:04:30', 5, null, 22);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-01-08 16:44:05', 5, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 23);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-08-07 02:45:47', 4, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 24);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-05-30 20:31:17', 1, 'Donec posuere metus vitae ipsum.', 25);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-10-05 10:56:12', 1, 'Aliquam non mauris. Morbi non lectus.', 26);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-07-30 17:46:54', 4, 'Duis at velit eu est congue elementum.', 27);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-03-25 00:45:55', 4, 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 28);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-07-28 09:12:14', 4, 'Praesent lectus.', 29);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-12-04 11:09:33', 2, 'Proin risus.', 30);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-10-05 22:21:04', 4, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 31);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-05-24 12:52:17', 2, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 32);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-01-21 13:35:38', 1, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 33);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-03-07 01:04:17', 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 34);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-09-18 04:43:21', 1, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 35);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-02-04 14:58:41', 2, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 36);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-07-16 19:53:20', 1, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 37);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-05-15 00:04:41', 5, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 38);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-08-19 15:51:21', 2, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 39);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-08-06 21:53:15', 4, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 40);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-04-08 16:27:34', 5, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 41);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-07-09 17:29:26', 3, null, 42);
insert into comment_entity (createdAt, rating, content, authorId) values ('2021-10-23 02:11:45', 1, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 43);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-05-18 00:52:10', 1, 'Aliquam erat volutpat. In congue.', 44);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-09-24 06:17:17', 4, 'Cras pellentesque volutpat dui.', 45);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-09-18 09:17:32', 4, 'Pellentesque at nulla.', 46);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-05-21 09:48:04', 5, 'Maecenas rhoncus aliquam lacus.', 47);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-07-21 23:01:29', 5, null, 48);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-05-01 11:59:04', 5, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 49);
insert into comment_entity (createdAt, rating, content, authorId) values ('2022-06-22 23:41:36', 5, 'Nunc rhoncus dui vel sem. Sed sagittis.', 50);
